services:
  beyla:
    image: grafana/beyla:1.7.0
    environment:
      - BEYLA_OPEN_PORT=8080
      - BEYLA_PROMETHEUS_PORT=8999
      - BEYLA_TRACE_PRINTER=text
    pid: "container:go-app"
    privileged: true
    ports:
      - "8999:8999"

  app:
    container_name: go-app
    build: .
    ports:
      - "8080:8080"

